name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (for non-critical issues only)
title: "[Security]: "
labels: ["security", "triage"]
assignees: ["sharehodl/security-team"]

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT SECURITY NOTICE ⚠️
        
        **For CRITICAL security vulnerabilities, DO NOT use this public issue template.**
        
        Instead, please report critical security issues privately to:
        - Email: security@sharehodl.io
        - Bug Bounty: https://sharehodl.io/security/bug-bounty
        
        Use this form only for:
        - Minor security improvements
        - Security-related feature requests
        - Non-critical security observations
        
        ---

  - type: dropdown
    id: severity
    attributes:
      label: Security Issue Severity
      description: How severe is this security issue?
      options:
        - Informational (security best practices, documentation)
        - Low (minimal security impact)
        - Medium (moderate security implications)
        - STOP - This should be reported privately (High/Critical)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: |
        Describe the security issue, improvement, or observation.
        **Do not include exploit details for medium+ severity issues.**
      placeholder: Describe the security concern...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: Which category does this security issue fall into?
      options:
        - Authentication/Authorization
        - Input Validation
        - Cryptography
        - Access Control
        - Information Disclosure
        - Configuration Security
        - Dependency Security
        - Network Security
        - Code Quality/Security
        - Documentation Security
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: |
        What could happen if this security issue is not addressed?
        (Keep general for medium severity issues)
      placeholder: Describe the potential security impact...
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - Module: [e.g., HODL, DEX, Governance]
        - Component: [e.g., API, CLI, Core]
        - File/Function: [if applicable]
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      value: |
        - ShareHODL Version: [e.g., v1.0.0]
        - Network: [testnet, mainnet, local]
        - Deployment: [docker, kubernetes, binary]
        - OS: [e.g., Ubuntu 20.04]

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: |
        For informational/low severity issues, provide steps to observe the issue.
        **Do not provide exploit steps for medium+ severity.**
      placeholder: |
        1. Step one
        2. Step two
        3. Observe issue

  - type: textarea
    id: recommendation
    attributes:
      label: Recommended Solution
      description: If you have suggestions for how to address this security issue
      placeholder: Describe your recommended approach to fix or improve this...

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Any relevant security references, standards, or documentation:
        - CVE numbers
        - OWASP guidelines
        - Security best practices
        - Related issues or discussions
      placeholder: |
        - OWASP: [link]
        - CVE: [if applicable]
        - Standards: [if applicable]

  - type: checkboxes
    id: checks
    attributes:
      label: Security Checklist
      description: Please confirm the following
      options:
        - label: This is NOT a critical security vulnerability (reported privately if critical)
          required: true
        - label: I have not included sensitive information or exploit details
          required: true
        - label: I have checked existing issues for duplicates
          required: true
        - label: I understand this will be public and may be seen by potential attackers
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information about this security issue