package types

import (
	"cosmossdk.io/errors"
)

// x/extbridge module sentinel errors
var (
	ErrBridgingDisabled        = errors.Register(ModuleName, 1, "bridging is disabled")
	ErrInvalidChain            = errors.Register(ModuleName, 2, "invalid external chain")
	ErrInvalidAsset            = errors.Register(ModuleName, 3, "invalid external asset")
	ErrChainNotSupported       = errors.Register(ModuleName, 4, "chain not supported")
	ErrAssetNotSupported       = errors.Register(ModuleName, 5, "asset not supported")
	ErrDepositNotFound         = errors.Register(ModuleName, 6, "deposit not found")
	ErrWithdrawalNotFound      = errors.Register(ModuleName, 7, "withdrawal not found")
	ErrTSSSessionNotFound      = errors.Register(ModuleName, 8, "TSS session not found")
	ErrInsufficientConfirmations = errors.Register(ModuleName, 9, "insufficient confirmations on external chain")
	ErrAlreadyAttested         = errors.Register(ModuleName, 10, "validator already attested to this deposit")
	ErrDepositCompleted        = errors.Register(ModuleName, 11, "deposit already completed")
	ErrDepositRejected         = errors.Register(ModuleName, 12, "deposit was rejected")
	ErrInsufficientTier        = errors.Register(ModuleName, 13, "insufficient validator tier")
	ErrNotValidator            = errors.Register(ModuleName, 14, "sender is not a validator")
	ErrInvalidAmount           = errors.Register(ModuleName, 15, "invalid amount")
	ErrAmountTooSmall          = errors.Register(ModuleName, 16, "amount below minimum")
	ErrAmountTooLarge          = errors.Register(ModuleName, 17, "amount exceeds maximum")
	ErrRateLimitExceeded       = errors.Register(ModuleName, 18, "rate limit exceeded")
	ErrCircuitBreakerActive    = errors.Register(ModuleName, 19, "circuit breaker is active")
	ErrWithdrawalTimelocked    = errors.Register(ModuleName, 20, "withdrawal is still timelocked")
	ErrWithdrawalNotReady      = errors.Register(ModuleName, 21, "withdrawal not ready for signing")
	ErrInvalidTSSSession       = errors.Register(ModuleName, 22, "invalid TSS session")
	ErrTSSSessionCompleted     = errors.Register(ModuleName, 23, "TSS session already completed")
	ErrTSSSessionFailed        = errors.Register(ModuleName, 24, "TSS session failed")
	ErrTSSTimeout              = errors.Register(ModuleName, 25, "TSS session timed out")
	ErrInvalidSignature        = errors.Register(ModuleName, 26, "invalid signature")
	ErrDuplicateDeposit        = errors.Register(ModuleName, 27, "duplicate deposit transaction")
	ErrInvalidRecipient        = errors.Register(ModuleName, 28, "invalid recipient address")
	ErrInvalidExternalAddress  = errors.Register(ModuleName, 29, "invalid external chain address")
	ErrInvalidTxHash           = errors.Register(ModuleName, 30, "invalid transaction hash")
	ErrConversionFailed        = errors.Register(ModuleName, 31, "asset conversion failed")
	ErrInsufficientBalance     = errors.Register(ModuleName, 32, "insufficient HODL balance")
	ErrMintFailed              = errors.Register(ModuleName, 33, "failed to mint HODL")
	ErrBurnFailed              = errors.Register(ModuleName, 34, "failed to burn HODL")
	ErrUnauthorized            = errors.Register(ModuleName, 35, "unauthorized: only governance can perform this action")
	ErrAddressBanned           = errors.Register(ModuleName, 36, "address is banned from using the bridge")
)
